apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: file-store
  name: file-store
spec:
  containers:
  - image: file-store
    name: file-store
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
