apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: h2
  name: h2
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8181
  - name: "1521"
    port: 1521
    targetPort: 1521
  selector:
    io.kompose.service: h2
status:
  loadBalancer: {}
