version: '3'
services:
  file-store:
    restart: on-failure
    build: ./nokia
    depends_on:
      - h2
    expose:
       - 8080
    ports:
       - 8080:8080
       
  h2:
   container_name: 'h2'
   hostname: 'h2'
   image: 1000kit/h2
   ports:
      - "8181:8181"
      - "1521:1521"
   volumes:
      - h2-data:/opt/h2-data
volumes:
    h2-data:     




